### ISSUE TITLE
运行时报错，语料库和label都是按read_me配置的，用的是自己的数据

### ISSUE THREAD

**Issue by leonJCY** [LunaBlack/RNN-Classification#12]
Traceback (most recent call last):
  File "train.py", line 141, in <module>
    main()
  File "train.py", line 63, in main
    train(args)
  File "train.py", line 72, in train
    data_loader = TextLoader(True, args.utils_dir, args.data_path, args.batch_size, args.seq_length, None, None)
  File "/Users/Leon/Desktop/RNN-Classification-master/utils.py", line 39, in __init__
    self.load_preprocessed(vocab_file, data_path)
  File "/Users/Leon/Desktop/RNN-Classification-master/utils.py", line 98, in load_preprocessed
    tensor_x = np.array(list(map(self.transform, data['text'])))
  File "/Users/Leon/Desktop/RNN-Classification-master/utils.py", line 54, in transform
    new_d = map(self.vocab.get, d[:self.seq_length])
TypeError: 'float' object has no attribute '__getitem__'

**Comment by sduchh** [comment]
@leonJCY  我也遇到同样的问题，请问你解决了吗？

**Comment by sduchh** [comment]
@leonJCY 你看下labels.pkl是否是按照{“类标号”:数字}来生成的，我开始也遇到了这个问题后来解决了。

**Comment by sduchh** [comment]
@leonJCY Have you solved this problem?

**Comment by sduchh** [comment]
@leonJCY I have solved this problem. Line in train.csv has no content but with label, such as ',Y'.

**Comment by wanesta** [comment]
@sduchh How did you make the labels.pkl file use your slef data.
