### ISSUE TITLE
TypeError:

### ISSUE THREAD

**Issue by jiangyan12** [LunaBlack/RNN-Classification#6]
我将数据换成了自己的数据，在test时遇到了这样的bug...
Traceback (most recent call last):
  File "test.py", line 159, in <module>
    main()
	
  File "test.py", line 49, in main
    accuracy(args)
	
  File "test.py", line 124, in accuracy
    data_loader = TextLoader(False, args.utils_dir, args.data_path, saved_args.batch_size, saved_args.seq_length, vocab, labels)
	
  File "/nlp/RNN-Classification-master/utils.py", line 47, in __init__
    self.load_preprocessed(None, data_path)
	
  File "/nlp/RNN-Classification-master/utils.py", line 99, in load_preprocessed
    self.tensor = np.c_[tensor_x, tensor_y].astype(int)	
TypeError: long() argument must be a string or a number, not 'NoneType'

**Comment by jiangyan12** [comment]
This error has been sloved. 
because some sentences in test-set are too long.
